settings:
    bungeecord: true
    essentials: false
    subServer: true
    discordChannel: 'SERVER_CHAT'
    serverName: 'lobby'
    ranking:
        enable: true
        prefix: true
    enable:
        protocolsupport:
            versions:
                PC:
                    1m13: true
                    1m12: true
                    1m11: true
                    1m10: true
                    1m9: true
                    1m8: true
                    1m7: false
                    1m6: false
                    1m5: false
                    1m4: false
                PE: true
    redis:
        hostname: 'localhost'
        port: 6379
        password: ''
config: