main: me.skorrloregaming.LinkServer
name: SkorrloreGamingLink
version: 1.0-SNAPSHOT
description: Plugin to provide basic functionality to a server
api-version: 1.13
commands:
    unsubscribe:
        description: Unsubscribe from news header and auto broadcaster
    debug:
        description: Enable or disable debugging of this plugin
    logger:
        description: Enable or disable in-game anticheat logging
        aliases: logging
    playtime-report:
        description: Gets the range of stored playtime information for a player
        aliases: [playtime-report, ptreport, ptr]
    playtime:
        description: Retrieves the play time for a given player
        aliases: pt
    desync:
        description: Unlink your alternative account from your primary account
        aliases: [unsync, desync-account, desyncaccount, unsync-account, unsyncaccount, unsynca, desynca, delink, delink-account, delinka, unlinka, unlink, unlink-account]
    sync:
        description: Link your alternative account with your primary account
        aliases: [sync-account, syncaccount, synca, link-account, linkaccount, link, linka]