main: me.skorrloregaming.link.LinkServer
name: SkorrloreGamingLink
version: 1.0-SNAPSHOT
description: Plugin to provide basic functionality to a server
api-version: 1.13
commands:
    unsubscribe:
        description: Unsubscribe from news header and auto broadcaster
    debug:
        description: Enable or disable debugging of this plugin
    logger:
        description: Enable or disable in-game anticheat logging
        aliases: logging